services:
  setup:
    container_name: setup
    build:
      context: .
      dockerfile: Dockerfile.loci
    volumes:
      - .:/loci
    environment:
      CI: "true" 
    command: sh -lc "pnpm install"
    restart: "no"

  workspace:
    container_name: workspace
    build:
      context: .
      dockerfile: Dockerfile.loci
    depends_on:
      setup:
        condition: service_completed_successfully
    volumes:
      - .:/loci
    command: sh -c "tail -f /dev/null"
    restart: "no"

  api:
    container_name: api
    build:
      context: .
      target: dev
      dockerfile: apps/api/Dockerfile
    depends_on:
      workspace:
          condition: service_started
      setup:
        condition: service_completed_successfully
    environment:
      NODE_ENV: development
    volumes:
      - .:/loci
    ports:
      - "3000:3000"

  www:
    container_name: www
    build:
      context: .
      target: dev
      dockerfile: apps/www/Dockerfile
    depends_on:
      setup:
        condition: service_completed_successfully
    volumes:
      - .:/loci
    ports:
      - "3001:3001"

