services:
  setup:
    container_name: setup
    build:
      context: .
      dockerfile: Dockerfile.loci
    volumes:
      - .:/loci
    environment:
      CI: "true" 
    command: sh -lc "pnpm install"
    restart: "no"

  workspace:
    container_name: workspace
    build:
      context: .
      dockerfile: Dockerfile.loci
    depends_on:
      setup:
        condition: service_completed_successfully
    volumes:
      - .:/loci
    command: sh -c "tail -f /dev/null"
    restart: "no"

  api:
    container_name: api
    build:
      context: .
      target: dev
      dockerfile: apps/api/Dockerfile
    depends_on:
      workspace:
          condition: service_started
      setup:
        condition: service_completed_successfully
    volumes:
      - .:/loci
    ports:
      - "3000:3000"

  www:
    container_name: www
    build:
      context: .
      target: dev
      dockerfile: apps/www/Dockerfile
    depends_on:
      setup:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3001/health || exit 1"]
      start_period: 10s
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - .:/loci
    ports:
      - "3001:3001"
  www-e2e:
    container_name: www-e2e
    profiles: ["e2e"]
    build:
      context: .
      target: dev
      dockerfile: apps/www/Dockerfile.e2e
    depends_on:
      setup:
        condition: service_completed_successfully
      www:
        condition: service_healthy
    volumes:
      - .:/loci

networks:
  default:
    name: loci
    driver: bridge

